version: "3.9"
services:
  vimgolf-db:
    image: "mariadb"
    volumes:
     - vimgolf-db-data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=vimgolf
      - MYSQL_USER=vimgolf
      - MYSQL_PASSWORD=${DB_PASSWORD}
  vimgolf-docker:
    image: "docker:dind"
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command: --tls=false
    volumes:
      - vimgolf-submissions:/tmp
  vimgolf-backend:
    build:
      context: .
    environment:
      - DOCKER_HOST=tcp://vimgolf-docker:2375
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://vimgolf:${DB_PASSWORD}@vimgolf-db/vimgolf
    volumes:
      - vimgolf-submissions:/tmp
    depends_on:
      - vimgolf-docker
volumes:
  vimgolf-submissions:
    external: true
  vimgolf-db-data:
networks:
  default:
    external:
      name: felicity_nw

